name: session_mate
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.9
  get: ^4.6.6
  flutter_screenutil: ^5.9.0
  connectivity: ^3.0.6
  pinput: ^4.0.0
  intl_phone_field: ^3.2.0
  webview_flutter: ^3.0.4
  cloud_firestore: ^4.1.0
  firebase_auth: ^4.10.0
  firebase_core:
  get_storage: ^2.1.1
  google_maps_flutter: ^2.2.5
  permission_handler: ^10.2.0
  geolocator: ^11.0.0
  geocoding: ^2.1.0
  month_picker_dialog: ^2.11.2
  intl: ^0.18.0
  octo_image: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/

  fonts:
    - family: Inter
      fonts:
        - asset: assets/fonts/Inter-Regular.otf
          weight: 400
        - asset: assets/fonts/Inter-SemiBold.otf
          weight: 600
        - asset: assets/fonts/Inter-Bold.otf
          weight: 700

